// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace whosnext.iOS
{
	public partial class GroupDetailScreenViewController : UIViewController
	{

		public int Index;

		public GroupDetailScreenViewController (IntPtr handle) : base (handle)
		{
		}


		public override void ViewDidLoad(){
			this.Title = "Group " + Index.ToString();
		}

	}
}
